version: "3.9"
services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    environment:
      - SERVER_PORT=8761
    networks:
      - default
      - microservices-monitoring

  api-gateway:
    build: ./api-gateway
    ports:
      - "8085:8085"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - default
      - microservices-monitoring

  proveedores-service:
    build: ./proveedores-service
    ports:
      - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - default
      - microservices-monitoring
    extra_hosts:
      - "host.docker.internal:host-gateway"

  productos-service:
    build: ./productos-service
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - default
      - microservices-monitoring
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ordenes-service:
    build: ./ordenes-service
    ports:
      - "8083:8083"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - default
      - microservices-monitoring
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  microservices-monitoring:
    external: true
